//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOCINAPharm.pages.Pharmacist
{


    public partial class Customers
    {

        /// <summary>
        /// litCustomerCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litCustomerCount;

        /// <summary>
        /// litTotalCustomers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTotalCustomers;

        /// <summary>
        /// litActiveCustomers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litActiveCustomers;

        /// <summary>
        /// litNewCustomers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litNewCustomers;

        /// <summary>
        /// litTotalPurchases control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litTotalPurchases;

        /// <summary>rptCards control (customer card grid view).</summary>
        protected global::System.Web.UI.WebControls.Repeater rptCards;

        /// <summary>rptTable control (customer table view).</summary>
        protected global::System.Web.UI.WebControls.Repeater rptTable;

        /// <summary>hdnAction control (CRUD bridge: add | edit).</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnAction;

        /// <summary>hdnCustomerId control (CRUD bridge).</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnCustomerId;

        /// <summary>hdnFullName control (CRUD bridge).</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnFullName;

        /// <summary>hdnPhone control (CRUD bridge).</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnPhone;

        /// <summary>hdnEmail control (CRUD bridge).</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnEmail;

        /// <summary>hdnDob control (CRUD bridge).</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnDob;

        /// <summary>hdnGender control (CRUD bridge).</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnGender;

        /// <summary>hdnAllergies control (CRUD bridge).</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnAllergies;

        /// <summary>hdnAddress control (CRUD bridge).</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnAddress;

        /// <summary>lnkPharmCRUD control (hidden postback trigger for CRUD bridge).</summary>
        protected global::System.Web.UI.WebControls.LinkButton lnkPharmCRUD;
    }
}
