//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOCINAPharm.pages.Pharmacist
{


    public partial class Prescriptions
    {

        /// <summary>
        /// litPendingCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litPendingCount;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// ddlStatusFilter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;

        /// <summary>
        /// txtDateFrom control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDateFrom;

        /// <summary>
        /// txtDateTo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtDateTo;

        /// <summary>
        /// upRxTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel upRxTable;

        /// <summary>
        /// litShowing control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal litShowing;

        /// <summary>
        /// upProgress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdateProgress upProgress;

        /// <summary>
        /// rxPatientName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox rxPatientName;

        /// <summary>
        /// rxDoctor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox rxDoctor;

        /// <summary>
        /// rxMedicines control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox rxMedicines;

        /// <summary>
        /// rxDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox rxDate;

        /// <summary>
        /// rxNotes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox rxNotes;

        /// <summary>
        /// ddlRxCustomer control — registered patient dropdown.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRxCustomer;

        /// <summary>
        /// hfMedicineItems control — JSON-serialised prescription line items.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfMedicineItems;

        /// <summary>rptRx control — prescriptions grid.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptRx;

        /// <summary>hfActionId control — status-change target id.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfActionId;

        /// <summary>hfEditId control — edit target id.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hfEditId;

        /// <summary>btnServerCreate control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnServerCreate;

        /// <summary>btnServerEditSave control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnServerEditSave;

        /// <summary>btnServerDispense control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnServerDispense;

        /// <summary>btnServerCancel control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton btnServerCancel;
    }
}
